---
- name: Generate a super secret password via pwgen
  command: pwgen -N 1 -s 96
  register: graylog_secret
 
- name: Generate a web console password via pwgen
  command: pwgen -N 1 -s 16
  register: webPassword
  
- name: Generate a password hash from web password
  shell: echo -n "{{ webPassword.stdout }}" | sha256sum | awk '{ print $1 }'
  register: passwordHash
  
- name: Create webConsole.txt (if it doesn't already exist)
  command: touch /var/log/webConsole.txt
  args:
    creates: /var/log/webConsole.txt  
  
- name: Place web console password in a file
  shell: echo "{{ webPassword.stdout }}" >> /var/log/webConsole.txt